default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres
 
development:
  <<: *default
  database: forms_development
 
test:
  <<: *default
  database: forms_test
 
production:
  <<: *default
  database: forms_production